//DOM element reference used in JS files
export const pageBody = document.querySelector('body');
export const logo = document.querySelector('#logo');
export const photographerList = document.querySelector('#photographer_list');
export const photographerTotalLikes = document.querySelector('#photographer_footer .like_count p');
export const contactButton = document.querySelector('#contact_button');
export const contactSend = document.querySelector('#contact_send');
export const contactClose = document.querySelector('#contact_close');
export const contactModal = document.querySelector('#contact_modal');
export const mediaList = document.querySelector('#media_list');
export const mediaLightbox = document.querySelector('#media_lightbox');
export const mediaTitle = document.querySelector('#media_lightbox .media_title');
export const mediaPrevious = document.querySelector('#media_prev');
export const mediaNext = document.querySelector('#media_next');
export const mediaClose = document.querySelector('#media_close');
export const mediaContainer = document.querySelector('.lightbox_media_container');
export const sortingList = document.querySelector('#media_sorting_list');
export const sortingExpandedIcon = document.querySelector('#media_sorting_list img');
export const sortingExpandedList = document.querySelector('#media_sortings_expanded');
export const sortingSelected = document.querySelector('.media_sorting[aria-selected="true"]');
export const sortingSelectedName = document.querySelector('.media_sorting[aria-selected="true"] p');
export const sortingOptions = document.querySelectorAll('.media_sorting[aria-selected="false"]');
